services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: go run main.go
    env_file: ./backend/.env
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

  ml_service:
    build:
      context: ./ml_service
    container_name: ml_service
    ports:
      - "8000:8000"
    env_file: ./ml_service/.env
    working_dir: /app
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - postgres

  postgres:
    image: ankane/pgvector:latest
    container_name: jetswitch_pg
    environment:
      POSTGRES_DB: jetswitch
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data  # fixed path!
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5430:5432"
    restart: unless-stopped


  pgadmin:
    image: dpage/pgadmin4
    container_name: jetswitch_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
volumes:
  postgres_data:
  pgadmin_data:
    external: false


