import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'Get Started' }).click();
  await page.getByRole('link', { name: 'Register here' }).click();
  await expect(page.locator('input[name="username"]')).toBeVisible();
  await expect(page.locator('input[name="email"]')).toBeVisible();
  await expect(page.locator('input[name="password"]')).toBeVisible();
  await expect(page.locator('input[name="confirm_password"]')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Register' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Login here' })).toBeVisible();
  await page.locator('input[name="username"]').click();
  await page.locator('input[name="username"]').fill('b');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('b@gmail.com');
  await page.locator('input[name="email"]').press('Tab');
  await page.locator('input[name="password"]').fill('bbbbbb');
  await page.locator('input[name="confirm_password"]').click();
  await page.locator('input[name="confirm_password"]').fill('bbbbbb');
  await page.getByRole('button', { name: 'Register' }).click();
  await expect(page.getByRole('heading', { name: '🎧 Listener' })).toBeVisible();
  await expect(page.getByRole('heading', { name: '🎤 Artist' })).toBeVisible();
  await page.getByRole('heading', { name: '🎤 Artist' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Get Started' }).click();
  await expect(page.getByRole('button', { name: 'Upload Track' })).toBeVisible();
  await page.getByRole('button', { name: 'Upload Track' }).click();
  await page.getByRole('textbox', { name: 'https://www.youtube.com/watch?v=' }).click();
  await page.getByRole('textbox', { name: 'https://www.youtube.com/watch?v=' }).fill('https://youtu.be/K-jwbV9FRFo?si=Kjd74M5e8ODSE8tO');
  await page.getByRole('textbox', { name: 'Enter song title' }).click();
  await page.getByRole('textbox', { name: 'Enter song title' }).fill('Heart of Ice');
  await page.getByRole('textbox', { name: 'Enter artist name' }).click();
  await page.getByRole('textbox', { name: 'Enter artist name' }).fill('BoyWithUke');
  await expect(page.getByRole('button', { name: 'Back' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Analyze' })).toBeVisible();
  await page.getByRole('button', { name: 'Analyze' }).click();
  await expect(page.getByText('Extracting...Analyzing your')).toBeVisible();
  await expect(page.locator('svg')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Heart of Ice' })).toBeVisible();
  await expect(page.getByText('BoyWithUke').first()).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Matching Result' })).toBeVisible();
  await page.getByRole('button', { name: 'Back' }).click();
});
