import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
	await page.goto('http://localhost:5173/');
	await page.getByRole('button', { name: 'JOIN US' }).click();
	await page.getByRole('link', { name: 'Register here' }).click();
	await expect(page.getByRole('heading', { name: 'Register' })).toBeVisible();
	await page.locator('input[name="username"]').click();
	await page.locator('input[name="username"]').fill('artist');
	await page.locator('input[name="email"]').click();
	await page.locator('input[name="email"]').fill('artist@example.com');
	await page.locator('input[name="password"]').click();
	await page.locator('input[name="password"]').fill('artistpassword');
	await page.locator('input[name="confirm_password"]').click();
	await page.locator('input[name="confirm_password"]').fill('artistpassword');
	await page.getByRole('button', { name: 'Register' }).click();
	await page.getByText('I create music and want to').click();
	await page.getByRole('button', { name: 'Continue' }).click();
	await page.getByRole('button', { name: 'LOGOUT' }).click();
	await page.getByRole('button', { name: 'JOIN US' }).click();
	await page.getByRole('link', { name: 'Register here' }).click();
	await page.locator('input[name="username"]').click();
	await page.locator('input[name="username"]').fill('listener');
	await page.locator('input[name="email"]').click();
	await page.locator('input[name="email"]').fill('listener@example.com');
	await page.locator('input[name="password"]').click();
	await page.locator('input[name="password"]').fill('listenerpassword');
	await page.locator('input[name="confirm_password"]').click();
	await page.locator('input[name="confirm_password"]').fill('listenerpassword');
	await page.getByRole('button', { name: 'Register' }).click();
	await page.getByRole('heading', { name: '🎧 Listener' }).click();
	await page.getByRole('button', { name: 'Continue' }).click();
	await page.getByRole('button', { name: 'LOGOUT' }).click();
	await page.getByRole('button', { name: 'JOIN US' }).click();
	await page.locator('input[name="username"]').click();
	await page.locator('input[name="username"]').fill('artist');
	await page.locator('input[name="password"]').click();
	await page.locator('input[name="password"]').fill('artistpassword');
	await page.getByRole('button', { name: 'Login' }).click();
	await expect(page.getByRole('heading', { name: 'Welcome back, artist!' })).toBeVisible();
	await expect(page.getByText('You are logged in as artist.')).toBeVisible();
	await page.getByRole('button', { name: 'LOGOUT' }).click();
	await page.getByRole('button', { name: 'JOIN US' }).click();
	await page.locator('input[name="username"]').click();
	await page.locator('input[name="username"]').fill('listener');
	await page.locator('input[name="password"]').click();
	await page.locator('input[name="password"]').fill('listenerpassword');
	await page.getByRole('button', { name: 'Login' }).click();
	await expect(page.getByRole('heading', { name: 'Welcome back, listener!' })).toBeVisible();
	await expect(page.getByText('You are logged in as listener.')).toBeVisible();
	await page.getByRole('button', { name: 'LOGOUT' }).click();
});
